spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia
    username: postgres
    password: 151430
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
